In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("healthcare_dataset.csv")

In [3]:
data.head()

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby JacksOn,NaN,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,NaN,Urgent,2024-02-02,Paracetamol,Normal
1,NaN,NaN,Male,A+,NaN,NaN,NaN,Kim Inc,Medicare,33643.327287,NaN,Emergency,NaN,Ibuprofen,Inconclusive
2,NaN,NaN,Female,NaN,Obesity,NaN,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205.0,Emergency,NaN,Aspirin,Normal
3,NaN,NaN,Female,O+,Diabetes,2020-11-18,Kevin Wells,NaN,Medicare,37909.782410,450.0,Elective,NaN,Ibuprofen,Abnormal
4,adrIENNE bEll,43.0,Female,NaN,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,NaN,458.0,Urgent,2022-10-09,Penicillin,Abnormal

In [4]:
data.tail()

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
55495,eLIZABeTH jaCkSOn,42.0,Female,NaN,Asthma,2020-08-16,Joshua Jarvis,Jones-Thompson,NaN,NaN,417.0,Elective,NaN,Penicillin,Abnormal
55496,KYle pEREz,61.0,Female,AB-,Obesity,2020-01-23,Taylor Sullivan,Tucker-Moyer,Cigna,31457.797307,316.0,Elective,2020-02-01,Aspirin,Normal
55497,HEATher WaNG,38.0,Female,B+,NaN,2020-07-13,Joe Jacobs DVM,"and Mahoney Johnson Vasquez,",UnitedHealthcare,27620.764717,347.0,Urgent,2020-08-10,NaN,Abnormal
55498,JENniFER JOneS,43.0,Male,O-,Arthritis,2019-05-25,NaN,NaN,NaN,32451.092358,321.0,Elective,2019-05-31,NaN,Abnormal
55499,NaN,NaN,Female,O+,Arthritis,2024-04-02,Dennis Warren,Henry Sons and,Aetna,NaN,448.0,Urgent,NaN,Ibuprofen,Abnormal

In [5]:
data.describe()

                Age  Billing Amount   Room Number
count  41280.000000    41371.000000  41393.000000
mean      51.570615    25471.996106    301.273718
std       19.639837    14205.269105    115.295924
min       13.000000    -2008.492140    101.000000
25%       35.000000    13142.422756    202.000000
50%       52.000000    25524.784827    302.000000
75%       68.000000    37690.177751    401.000000
max       89.000000    52764.276736    500.000000

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55500 entries, 0 to 55499
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Name                41360 non-null  object
 1   Age                 41280 non-null  float64
 2   Gender              41467 non-null  object
 3   Blood Type          41500 non-null  object
 4   Medical Condition   41321 non-null  object
 5   Date of Admission   41428 non-null  object
 6   Doctor              41398 non-null  object
 7   Hospital            41569 non-null  object
 8   Insurance Provider  41513 non-null  object
 9   Billing Amount      41371 non-null  float64
 10  Room Number         41393 non-null  float64
 11  Admission Type      41248 non-null  object
 12  Discharge Date      41448 non-null  object
 13  Medication          41388 non-null  object
 14  Test Results        55500 non-null  object
dtypes: float64(3), object(12)
memory usage: 6.4+ MB

In [7]:
threshold = data.shape[1]*0.4

In [8]:
threshold

6.0

In [9]:
data.to_csv("cleaned_copy.csv")

In [17]:
row_null_ratio = data.isna().sum(axis=1)
count = (row_null_ratio> threshold).sum()

In [18]:
count

np.int64(4531)

In [20]:
data[row_null_ratio> threshold]

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
1,NaN,NaN,Male,A+,NaN,NaN,NaN,Kim Inc,Medicare,33643.327287,NaN,Emergency,NaN,Ibuprofen,Inconclusive
16,NaN,NaN,NaN,A+,NaN,2020-06-23,Erica Spencer,Cervantes-Wells,NaN,24499.847904,NaN,Elective,2020-07-14,NaN,Normal
19,dANIEL schmIdt,63.0,Male,NaN,NaN,NaN,NaN,NaN,NaN,23762.203579,465.0,NaN,NaN,NaN,Normal
36,DEnIse ToRRES,33.0,NaN,AB+,Diabetes,NaN,NaN,NaN,Aetna,4397.776995,481.0,NaN,NaN,NaN,Inconclusive
37,CasSAndrA Robinson,26.0,Female,B-,Hypertension,NaN,Travis Parsons,NaN,NaN,NaN,NaN,Urgent,NaN,NaN,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55464,NaN,35.0,Female,AB-,NaN,2024-02-28,NaN,NaN,NaN,11889.154513,128.0,NaN,NaN,Paracetamol,Abnormal
55472,NaN,NaN,NaN,AB-,NaN,2020-05-11,Breanna Norris,Deleon-Davis,NaN,30480.998859,280.0,NaN,NaN,NaN,Normal
55476,NaN,31.0,Female,NaN,NaN,2020-07-24,NaN,Johnson-Dixon,NaN,42279.166981,NaN,Emergency,NaN,Lipitor,Normal
55479,NaN,NaN,NaN,B-,Cancer,2022-01-05,Andrea Fields,NaN,Medicare,45767.175201,NaN,NaN,NaN,Ibuprofen,Normal
55485,NaN,41.0,Female,NaN,Asthma,2020-10-06,Leslie Lowe,NaN,Medicare,NaN,182.0,NaN,NaN,NaN,Abnormal

In [25]:
data.dropna(thres=threshold)

TypeError: DataFrame.dropna() got an unexpected keyword argument 'thres'

In [1]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["A", "B"],
    "Math": [90, 80],
    "Science": [85, 75]
})

melted = pd.melt(df, id_vars=["Name"], var_name="Subject", value_name="Marks")
print(melted)

  Name  Subject  Marks
0    A     Math     90
1    B     Math     80
2    A  Science     85
3    B  Science     75